reviving pytest (#15)
CI steps for building llvm and imex

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,46 +1,116 @@
+name: GitHub Actions Demo
+run-name: ${{ github.actor }} CI for ddpt
 on: [push, pull_request]
-
 defaults:
   run:
     shell: bash
-
 jobs:
   build_and_test:
-    name: building and testing ddptensor
     runs-on: [self-hosted, dds-base]
-    container:
-      image: amr-registry-pre.caas.intel.com/tpi/ddpt
-      options: --device=/dev/dri --shm-size=3000M
     strategy:
       fail-fast: false
+    env:
+      MLIRROOT: /localdisk/llvm/curr
+      IMEXROOT: third_party/install/imex
     steps:
-    - name: Setup
-      run: . activate ddpt
-    - name: Checkout ddptensor and submodules
-      uses: actions/checkout@v2
-      with:
-        submodules: recursive
-    - name: Build dpptensor
-      run: |
-        . activate ddpt
-        g++ -v
-        export MPIROOT=$CONDA_PREFIX
-        export MKLROOT=$CONDA_PREFIX
-        CMAKE_BUILD_PARALLEL_LEVEL=8 python setup.py develop
-    - name: Run tests
-      run: |
-        . activate ddpt
-        pytest test
-        DDPT_CW=0 pytest test
-        DDPT_CW=1 pytest test
-        DDPT_MPI_SPAWN=1 PYTHON_EXE=`which python` pytest test
-        DDPT_MPI_SPAWN=2 PYTHON_EXE=`which python` pytest test
-        DDPT_MPI_SPAWN=3 PYTHON_EXE=`which python` pytest test
-        DDPT_CW=1 mpirun -n 1 python -m pytest test
-        DDPT_CW=1 mpirun -n 2 python -m pytest test
-        DDPT_CW=1 mpirun -n 3 python -m pytest test
-        DDPT_CW=1 mpirun -n 4 python -m pytest test
-        DDPT_CW=0 mpirun -n 1 python -m pytest test
-        DDPT_CW=0 mpirun -n 2 python -m pytest test
-        DDPT_CW=0 mpirun -n 3 python -m pytest test
-        DDPT_CW=0 mpirun -n 4 python -m pytest test
+      - name: Check repo
+        uses: actions/checkout@v3
+        with:
+          submodules: recursive
+      - name: Setup IMEX Cache Var
+        run: |
+          echo 'IMEX_SHA<<EOF' >> $GITHUB_ENV
+          cat imex_version.txt >> $GITHUB_ENV
+          echo 'EOF' >> $GITHUB_ENV
+      - name: Echo IMEX SHA
+        run: echo ${{ env.IMEX_SHA }}
+      - name: Checkout IMEX
+        uses: actions/checkout@v3
+        with:
+          repository: intel-innersource/frameworks.ai.mlir.mlir-extensions
+          token: ${{ secrets.PATIMEX }}
+          path: third_party/imex
+          ref: ${{ env.IMEX_SHA }}
+      - name: Setup LLVM Cache Vars
+        run: |
+          echo 'LLVM_SHA<<EOF' >> $GITHUB_ENV
+          cat third_party/imex/build_tools/llvm_version.txt >> $GITHUB_ENV
+          echo 'EOF' >> $GITHUB_ENV
+      - name: Echo LLVM SHA
+        run: echo ${{ env.LLVM_SHA }}
+      - name: Miniconda
+        run: |
+          mkdir -p "$GITHUB_WORKSPACE"/third_party/install
+          cd "$GITHUB_WORKSPACE"/third_party
+          wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
+          bash Miniconda3-latest-Linux-x86_64.sh -u -b -f -p $GITHUB_WORKSPACE/third_party/install/miniconda
+          echo "$GITHUB_WORKSPACE/third_party/install/miniconda/bin" >> $GITHUB_PATH
+          echo "$GITHUB_WORKSPACE/third_party/install/miniconda/condabin" >> $GITHUB_PATH
+          export PATH=$GITHUB_WORKSPACE/third_party/install/miniconda/bin:${PATH}
+          . $GITHUB_WORKSPACE/third_party/install/miniconda/etc/profile.d/conda.sh
+          . $GITHUB_WORKSPACE/third_party/install/miniconda/bin/activate
+          which conda
+          which python
+          conda create -q -n ddpt -c intel -c defaults pybind11 numpy cmake ninja impi-devel libstdcxx-ng mpi4py pytest scipy tbb-devel
+          cd -
+      - name: Cache LLVM-MLIR
+        id: cache-llvm-mlir
+        uses: actions/cache@v3
+        env:
+          LLVM_CACHE_NUMBER: 1  # Increase to reset cache
+        with:
+          path: third_party/install/llvm-mlir/**
+          key: ${{ runner.os }}-build-llvm-${{ env.LLVM_CACHE_NUMBER }}-${{ env.LLVM_SHA }}
+      - name: Build LLVM MLIR
+        if: steps.cache-llvm-mlir.outputs.cache-hit != 'true'
+        run: |
+          echo "INFO: Need to rebuild LLVM-MLIR. Previous installation for MLIR not found"
+          . $GITHUB_WORKSPACE/third_party/install/miniconda/etc/profile.d/conda.sh
+          . $GITHUB_WORKSPACE/third_party/install/miniconda/bin/activate ddpt
+          np=`nproc`
+          pushd third_party
+          if [ -d "llvm-project" ]; then rm -rf llvm-project; fi
+          mkdir llvm-project || exit 1
+          cd llvm-project || exit 1
+          git init
+          git remote add origin https://github.com/llvm/llvm-project || exit 1
+          git fetch origin ${{ env.LLVM_SHA }} || exit 1
+          git reset --hard FETCH_HEAD || exit 1
+          if [ -d "$GITHUB_WORKSPACE/third_party/imex/build_tools/patches" ]; then git apply $GITHUB_WORKSPACE/third_party/imex/build_tools/patches/*.patch; fi
+          cd -
+          mkdir -p build/llvm-mlir || exit 1
+          cd build/llvm-mlir || exit 1
+          cmake ../../llvm-project/llvm -GNinja -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_PROJECTS=mlir -DLLVM_ENABLE_ASSERTIONS=ON -DLLVM_ENABLE_RTTI=ON -DLLVM_INSTALL_UTILS=ON -DLLVM_TARGETS_TO_BUILD=X86 -DLLVM_ENABLE_BINDINGS=OFF -DLLVM_ENABLE_ZSTD=OFF -DLLVM_DISTRIBUTION_COMPONENTS="llvm-headers;llvm-libraries;cmake-exports;FileCheck;count;not;mlir-headers;mlir-libraries;mlir-cmake-exports;mlir-tblgen;mlir-cpu-runner" -DCMAKE_INSTALL_PREFIX="$GITHUB_WORKSPACE"/third_party/install/llvm-mlir
+          cmake --build . -j ${np} || exit 1
+          cmake --install . || exit 1
+          cp bin/FileCheck $GITHUB_WORKSPACE/third_party/install/llvm-mlir/bin/
+          cp bin/count $GITHUB_WORKSPACE/third_party/install/llvm-mlir/bin/
+          cp bin/not $GITHUB_WORKSPACE/third_party/install/llvm-mlir/bin/
+          popd
+          ls $GITHUB_WORKSPACE/third_party/install/llvm-mlir/
+          ls third_party/install/llvm-mlir/
+
+      - name: Cache IMEX
+        id: cache-imex-mlir
+        uses: actions/cache@v3
+        env:
+          IMEX_CACHE_NUMBER: 1  # Increase to reset cache
+        with:
+          path: third_party/install/imex/**
+          key: ${{ runner.os }}-build-imex-${{ env.IMEX_CACHE_NUMBER }}-${{ env.IMEX_SHA }}
+      - name: Build IMEX
+        if: steps.cache-imex-mlir.outputs.cache-hit != 'true'
+        run: |
+          which python
+          . $GITHUB_WORKSPACE/third_party/install/miniconda/etc/profile.d/conda.sh
+          . $GITHUB_WORKSPACE/third_party/install/miniconda/bin/activate ddpt
+          mkdir -p third_party/build/imex
+          pushd third_party/build/imex
+          MLIR_DIR=$GITHUB_WORKSPACE/third_party/install/llvm-mlir cmake $GITHUB_WORKSPACE/third_party/imex -DCMAKE_BUILD_TYPE=debug -G Ninja
+          cmake --build . -j ${np} || exit 1
+          cmake --install . --prefix=$GITHUB_WORKSPACE/third_party/install/imex || exit 1
+          popd
+          ls $GITHUB_WORKSPACE/third_party/install/imex
+          ls third_party/install/imex
+      - run: |
+          echo "This job's status is ${{ job.status }}."
